pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
    }
    stages {
        stage('Build Image') {
            steps {
                script {
                    docker.build("yourdockerhubusername/secure-ci-app")
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("yourdockerhubusername/secure-ci-app").push('latest')
                    }
                }
            }
        }
    }
}
